// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/dir_merc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mercenario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Id     int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Mercenario) Reset() {
	*x = Mercenario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mercenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mercenario) ProtoMessage() {}

func (x *Mercenario) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mercenario.ProtoReflect.Descriptor instead.
func (*Mercenario) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{0}
}

func (x *Mercenario) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Mercenario) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Piso struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numero     int32       `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Decision   int32       `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Mercenario *Mercenario `protobuf:"bytes,3,opt,name=mercenario,proto3" json:"mercenario,omitempty"`
}

func (x *Piso) Reset() {
	*x = Piso{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Piso) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piso) ProtoMessage() {}

func (x *Piso) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piso.ProtoReflect.Descriptor instead.
func (*Piso) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{1}
}

func (x *Piso) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Piso) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

func (x *Piso) GetMercenario() *Mercenario {
	if x != nil {
		return x.Mercenario
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{3}
}

type DoshBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto int32 `protobuf:"varint,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *DoshBank) Reset() {
	*x = DoshBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoshBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoshBank) ProtoMessage() {}

func (x *DoshBank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoshBank.ProtoReflect.Descriptor instead.
func (*DoshBank) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{4}
}

func (x *DoshBank) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type DecisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mercenario string `protobuf:"bytes,1,opt,name=Mercenario,proto3" json:"Mercenario,omitempty"`
	Piso       int32  `protobuf:"varint,2,opt,name=Piso,proto3" json:"Piso,omitempty"`
	Decision   string `protobuf:"bytes,3,opt,name=Decision,proto3" json:"Decision,omitempty"`
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionRequest) GetMercenario() string {
	if x != nil {
		return x.Mercenario
	}
	return ""
}

func (x *DecisionRequest) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *DecisionRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

type DecisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{6}
}

func (x *DecisionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDecisionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDecisionsRequest) Reset() {
	*x = GetDecisionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionsRequest) ProtoMessage() {}

func (x *GetDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionsRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{7}
}

type GetDecisionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decisions []string `protobuf:"bytes,1,rep,name=Decisions,proto3" json:"Decisions,omitempty"`
}

func (x *GetDecisionsResponse) Reset() {
	*x = GetDecisionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionsResponse) ProtoMessage() {}

func (x *GetDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionsResponse.ProtoReflect.Descriptor instead.
func (*GetDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{8}
}

func (x *GetDecisionsResponse) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type FetchDecisionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchDecisionsRequest) Reset() {
	*x = FetchDecisionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDecisionsRequest) ProtoMessage() {}

func (x *FetchDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDecisionsRequest.ProtoReflect.Descriptor instead.
func (*FetchDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{9}
}

type FetchDecisionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decisions []string `protobuf:"bytes,1,rep,name=Decisions,proto3" json:"Decisions,omitempty"`
}

func (x *FetchDecisionsResponse) Reset() {
	*x = FetchDecisionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDecisionsResponse) ProtoMessage() {}

func (x *FetchDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDecisionsResponse.ProtoReflect.Descriptor instead.
func (*FetchDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{10}
}

func (x *FetchDecisionsResponse) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type StartMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionId    string  `protobuf:"bytes,1,opt,name=MissionId,proto3" json:"MissionId,omitempty"`
	MercenaryIds []int32 `protobuf:"varint,2,rep,packed,name=MercenaryIds,proto3" json:"MercenaryIds,omitempty"`
}

func (x *StartMissionRequest) Reset() {
	*x = StartMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMissionRequest) ProtoMessage() {}

func (x *StartMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMissionRequest.ProtoReflect.Descriptor instead.
func (*StartMissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{11}
}

func (x *StartMissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *StartMissionRequest) GetMercenaryIds() []int32 {
	if x != nil {
		return x.MercenaryIds
	}
	return nil
}

type StartMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartMissionResponse) Reset() {
	*x = StartMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMissionResponse) ProtoMessage() {}

func (x *StartMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMissionResponse.ProtoReflect.Descriptor instead.
func (*StartMissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{12}
}

type OrderUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryId int32  `protobuf:"varint,1,opt,name=MercenaryId,proto3" json:"MercenaryId,omitempty"`
	NewOrder    string `protobuf:"bytes,2,opt,name=NewOrder,proto3" json:"NewOrder,omitempty"`
}

func (x *OrderUpdateRequest) Reset() {
	*x = OrderUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateRequest) ProtoMessage() {}

func (x *OrderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateRequest.ProtoReflect.Descriptor instead.
func (*OrderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{13}
}

func (x *OrderUpdateRequest) GetMercenaryId() int32 {
	if x != nil {
		return x.MercenaryId
	}
	return 0
}

func (x *OrderUpdateRequest) GetNewOrder() string {
	if x != nil {
		return x.NewOrder
	}
	return ""
}

type OrderUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *OrderUpdateResponse) Reset() {
	*x = OrderUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dir_merc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResponse) ProtoMessage() {}

func (x *OrderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dir_merc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResponse.ProtoReflect.Descriptor instead.
func (*OrderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_dir_merc_proto_rawDescGZIP(), []int{14}
}

func (x *OrderUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_dir_merc_proto protoreflect.FileDescriptor

var file_proto_dir_merc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x72, 0x5f, 0x6d, 0x65, 0x72, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x22, 0x34, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x04, 0x50, 0x69, 0x73, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x24, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x44,
	0x6f, 0x73, 0x68, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x61, 0x0a,
	0x0f, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x69, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x50, 0x69, 0x73, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x2c, 0x0a, 0x10, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x15,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x57, 0x0a, 0x13,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x64, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a,
	0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0x49, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xbd, 0x02, 0x0a,
	0x08, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f,
	0x50, 0x69, 0x73, 0x6f, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x2e, 0x50, 0x69, 0x73, 0x6f, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0e,
	0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x50, 0x69, 0x73, 0x6f, 0x12, 0x10,
	0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x69, 0x73, 0x6f,
	0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x72, 0x44, 0x6f, 0x73, 0x68, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x11, 0x2e, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x14,
	0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x44, 0x6f, 0x73, 0x68,
	0x42, 0x61, 0x6e, 0x6b, 0x12, 0x46, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x6f, 0x50, 0x61, 0x72,
	0x61, 0x53, 0x69, 0x67, 0x75, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x50, 0x69, 0x73, 0x6f, 0x12, 0x16,
	0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb3, 0x01, 0x0a,
	0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x44,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1f, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xb6, 0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb4, 0x01, 0x0a, 0x0f,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x51, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x1e, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x4c, 0x41, 0x42, 0x5f, 0x34, 0x44, 0x49, 0x53, 0x54, 0x52,
	0x49, 0x42, 0x55, 0x49, 0x44, 0x4f, 0x53, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dir_merc_proto_rawDescOnce sync.Once
	file_proto_dir_merc_proto_rawDescData = file_proto_dir_merc_proto_rawDesc
)

func file_proto_dir_merc_proto_rawDescGZIP() []byte {
	file_proto_dir_merc_proto_rawDescOnce.Do(func() {
		file_proto_dir_merc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dir_merc_proto_rawDescData)
	})
	return file_proto_dir_merc_proto_rawDescData
}

var file_proto_dir_merc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_dir_merc_proto_goTypes = []interface{}{
	(*Mercenario)(nil),             // 0: mercenario.Mercenario
	(*Piso)(nil),                   // 1: mercenario.Piso
	(*Response)(nil),               // 2: mercenario.Response
	(*Vacio)(nil),                  // 3: mercenario.Vacio
	(*DoshBank)(nil),               // 4: mercenario.DoshBank
	(*DecisionRequest)(nil),        // 5: mercenario.DecisionRequest
	(*DecisionResponse)(nil),       // 6: mercenario.DecisionResponse
	(*GetDecisionsRequest)(nil),    // 7: mercenario.GetDecisionsRequest
	(*GetDecisionsResponse)(nil),   // 8: mercenario.GetDecisionsResponse
	(*FetchDecisionsRequest)(nil),  // 9: mercenario.FetchDecisionsRequest
	(*FetchDecisionsResponse)(nil), // 10: mercenario.FetchDecisionsResponse
	(*StartMissionRequest)(nil),    // 11: mercenario.StartMissionRequest
	(*StartMissionResponse)(nil),   // 12: mercenario.StartMissionResponse
	(*OrderUpdateRequest)(nil),     // 13: mercenario.OrderUpdateRequest
	(*OrderUpdateResponse)(nil),    // 14: mercenario.OrderUpdateResponse
}
var file_proto_dir_merc_proto_depIdxs = []int32{
	0,  // 0: mercenario.Piso.mercenario:type_name -> mercenario.Mercenario
	0,  // 1: mercenario.Director.Preparacion:input_type -> mercenario.Mercenario
	1,  // 2: mercenario.Director.InicioPiso:input_type -> mercenario.Piso
	1,  // 3: mercenario.Director.DecisionesPiso:input_type -> mercenario.Piso
	3,  // 4: mercenario.Director.ConsultarDoshBank:input_type -> mercenario.Vacio
	0,  // 5: mercenario.Director.ListoParaSiguientePiso:input_type -> mercenario.Mercenario
	5,  // 6: mercenario.NameNodeService.RegisterDecision:input_type -> mercenario.DecisionRequest
	7,  // 7: mercenario.NameNodeService.GetDecisions:input_type -> mercenario.GetDecisionsRequest
	5,  // 8: mercenario.DataNodeService.StoreDecision:input_type -> mercenario.DecisionRequest
	9,  // 9: mercenario.DataNodeService.FetchDecisions:input_type -> mercenario.FetchDecisionsRequest
	11, // 10: mercenario.DirectorService.StartMission:input_type -> mercenario.StartMissionRequest
	13, // 11: mercenario.DirectorService.UpdateOrder:input_type -> mercenario.OrderUpdateRequest
	2,  // 12: mercenario.Director.Preparacion:output_type -> mercenario.Response
	2,  // 13: mercenario.Director.InicioPiso:output_type -> mercenario.Response
	2,  // 14: mercenario.Director.DecisionesPiso:output_type -> mercenario.Response
	4,  // 15: mercenario.Director.ConsultarDoshBank:output_type -> mercenario.DoshBank
	2,  // 16: mercenario.Director.ListoParaSiguientePiso:output_type -> mercenario.Response
	6,  // 17: mercenario.NameNodeService.RegisterDecision:output_type -> mercenario.DecisionResponse
	8,  // 18: mercenario.NameNodeService.GetDecisions:output_type -> mercenario.GetDecisionsResponse
	6,  // 19: mercenario.DataNodeService.StoreDecision:output_type -> mercenario.DecisionResponse
	10, // 20: mercenario.DataNodeService.FetchDecisions:output_type -> mercenario.FetchDecisionsResponse
	12, // 21: mercenario.DirectorService.StartMission:output_type -> mercenario.StartMissionResponse
	14, // 22: mercenario.DirectorService.UpdateOrder:output_type -> mercenario.OrderUpdateResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dir_merc_proto_init() }
func file_proto_dir_merc_proto_init() {
	if File_proto_dir_merc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dir_merc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mercenario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Piso); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoshBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDecisionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDecisionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDecisionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchDecisionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dir_merc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dir_merc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_dir_merc_proto_goTypes,
		DependencyIndexes: file_proto_dir_merc_proto_depIdxs,
		MessageInfos:      file_proto_dir_merc_proto_msgTypes,
	}.Build()
	File_proto_dir_merc_proto = out.File
	file_proto_dir_merc_proto_rawDesc = nil
	file_proto_dir_merc_proto_goTypes = nil
	file_proto_dir_merc_proto_depIdxs = nil
}
